
package com.itcast.bos.fore.utils.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.itcast.com/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<com.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomersNotAssociated", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindCustomersNotAssociated")
    @ResponseWrapper(localName = "findCustomersNotAssociatedResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindCustomersNotAssociatedResponse")
    public List<Customer> findCustomersNotAssociated();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.RegistResponse")
    public void regist(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "assignCustomer2fixedArea")
    @RequestWrapper(localName = "assignCustomer2fixedArea", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.AssignCustomer2FixedArea")
    @ResponseWrapper(localName = "assignCustomer2fixedAreaResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.AssignCustomer2FixedAreaResponse")
    public void assignCustomer2FixedArea(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.UpdateCustomerResponse")
    public void updateCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomersAssociated", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindCustomersAssociated")
    @ResponseWrapper(localName = "findCustomersAssociatedResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindCustomersAssociatedResponse")
    public List<Customer> findCustomersAssociated(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephoneAndPassword", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindByTelephoneAndPassword")
    @ResponseWrapper(localName = "findByTelephoneAndPasswordResponse", targetNamespace = "http://service.crm.itcast.com/", className = "com.itcast.crm.service.FindByTelephoneAndPasswordResponse")
    public Customer findByTelephoneAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
