
package com.itcast.crm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.itcast.crm.dao.CustomerDao;
import com.itcast.crm.domain.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService
 public interface CustomerService {
  List<Customer> findAll() ;
  //查找没有关联定区的
  List<Customer> findCustomersNotAssociated() ;
  //查询已经关联指定定区id的
 List<Customer> findCustomersAssociated( String fixedAreaId) ;
   
//将集合中customer的fixedAreaId全部改为传进来的定区id.就完成了将客户关联到这个定区中了
   void assignCustomer2fixedArea(String fixedAreaId, List<Integer> customerIds);
 //保存一个customer
 void regist(Customer customer);
 
 Customer findByTelephone(String telephone);
 void updateCustomer(String telephone);
 Customer findByTelephoneAndPassword(String Telephone,String Password);
 
 String  findByAddress(String sendAddress);
}
